version: '3.8'

services:
 mysql:
   
   image: mysql:5.7
   restart: unless-stopped
   env_file: ./.env
   environment:
     - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
     - MYSQL_DATABASE=$MYSQLDB_DATABASE
   ports:
     - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
   volumes:
     - db:/var/lib/mysql

 backend:
   
   build: ./firesave-api
   restart: unless-stopped
   env_file: ./.env
   ports:
     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
     - 4444:4444
   environment:
     - DB_HOST=mysql
     - DB_USER=$MYSQLDB_USER
     - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
     - DB_NAME=$MYSQLDB_DATABASE
     - DB_PORT=$MYSQLDB_DOCKER_PORT
   stdin_open: true
   tty: true
  
 frontend:
    build: ./ng-firesave/
    ports:
           - "80:80"      

volumes: 
 db:

